### ISSUE TITLE
Variabelen bij elkaar zetten en pas na de imports

### ISSUE THREAD

**Issue by koeenm** [Jason2426/user-experience-enhanced-website#4]
Om een duidelijker overzicht van je variabelen te houden kan je alles bij elkaar zetten

https://github.com/Jason2426/user-experience-enhanced-website/blob/1d3ddd1740edd24abda3a83bf7d61ce56d1b3546/server.js#L6C1-L32C58

**Comment by Jason2426** [comment]
Thx, **[Oplossing](https://github.com/Jason2426/user-experience-enhanced-website/blob/e19bac737b0f988f18003069747d281f955581e4/server.js#L22-L33)**
