### ISSUE TITLE
Event.preventDefault(); staat boven aan je functie

### ISSUE THREAD

**Issue by Jesse-Kramer** [Jason2426/user-experience-enhanced-website#5]
Als de functie errored werkt je hele form niet. Je kunt beter event.preventDefault(); onderaan je functie zetten.

**Comment by Jason2426** [comment]
Klopt inderdaad, tijgertje dankjewel. **[Oplossing](https://github.com/Jason2426/user-experience-enhanced-website/blob/e19bac737b0f988f18003069747d281f955581e4/public/scripts/script.js#L52-L79)**
